flux:
  base_model: "./models/flux1-dev-fp8.safetensors"
  fallback_base_model: "black-forest-labs/FLUX.1-dev"
  flux_dtype: 'fp8'  # Usar fp8 quantizado para reduzir uso de memória
  cpu_offload: true
  image_height: 640
  image_width: 1280
  lora: "./checkpoint/flux_lora/rgb_normal.safetensors"
  controlnet: "InstantX/FLUX.1-dev-Controlnet-Union"
  controlnet_modes: ["tile", "canny"]
  controlnet_guidance_start: [0.0, 0.05]
  controlnet_guidance_end: [0.65, 0.9]
  controlnet_conditioning_scale: [0.6, 0.4]
  controlnet_kernel_size: 45
  controlnet_sigma: 1.5
  controlnet_down_scale: 1
  redux: "black-forest-labs/FLUX.1-Redux-dev"
  num_inference_steps: 30
  num_inference_steps_fast: 20
  seed: 42
  device: 'cuda:0'

multiview:
  base_model: "sudo-ai/zero123plus-v1.1"  # Fallback para HuggingFace se modelo local não disponível
  local_model: "./models/zero123plus"  # ✅ Usar modelo local (tem prioridade) - relativo ao Kiss3DGen/
  custom_pipeline: "./models/zero123plus"  # Caminho relativo ao diretório Kiss3DGen/
  unet: "./checkpoint/zero123++/flexgen.ckpt"
  num_inference_steps: 32
  num_inference_steps_fast: 24
  image_height: 768
  image_width: 768
  grid_rows: 2
  grid_cols: 2
  seed: 42
  device: 'cuda:0'  # ✅ GPU para melhor performance

reconstruction:
  model_config: "./models/lrm/config/PRM_inference.yaml"
  base_model: "./checkpoint/lrm/final_ckpt.ckpt"
  device: 'cuda:0'
  stage2_steps: 60
  stage2_steps_fast: 40

caption:
  base_model: "multimodalart/Florence-2-large-no-flash-attn"
  device: 'cpu'

llm:
  base_model: "meta-llama/Llama-3.2-3B-Instruct"
  device: 'cpu'

use_zero_gpu: false # for huggingface demo only
3d_bundle_templates: './init_3d_Bundle'

img2img_defaults:
  redux_strength: 0.4
  primary_strength: 0.55
  guidance_scale: 7.0

# Perfis de qualidade (aplicados em tempo de inicialização)
quality_mode: "balanced"
quality_modes:
  fast:
    flux_steps: 20
    flux_guidance: 5.0
    isomer_stage1: 20
    isomer_stage2: 45
  balanced:
    flux_steps: 30
    flux_guidance: 7.0
    isomer_stage1: 25
    isomer_stage2: 60
  high:
    flux_steps: 50
    flux_guidance: 7.0
    isomer_stage1: 30
    isomer_stage2: 80

controlnet_defaults:
  modes: ["gray"]
  guidance_start: 0.0
  guidance_end: 0.9
  conditioning_scale: 1.1
  preprocess_kwargs:
    gray:
      save_intermediate_results: false